Repository ccfddl/ccf-deadlines, pull requests merged in 2021-05, with the labels that each got.

#21 Update CRYPTO 2021
  conference/SC/asiacrypt.yml
  conference/SC/ccs.yml
  conference/SC/crypto.yml
  conference/SC/esorics.yml
  conference/SC/eurocrypt.yml
  conference/SC/ndss.yml
  conference/SC/pkc.yml
  conference/SC/sp.yml
  conference/SC/tcc.yml
  conference/SC/uss.yml
Labels: status/LGT1, updateconf

#22 Add ICDM 2021
  conference/DB/icdm.yml
Labels: updateconf

#23 Update ICRA 2022
  conference/AI/icra.yml
Labels: updateconf

#26 Update ICTAI 2021
  conference/AI/ictai.yml
Labels: status/LGT1, updateconf

#27 Update EDBT 2022
  conference/DB/edbt.yml
Labels: ready-to-merge, updateconf

#28 Update ICDT 2022
  conference/DB/icdt.yml
Labels: ready-to-merge, updateconf

#29 Update ASPLOS 2022
  conference/DS/asplos.yml
Labels: ready-to-merge, updateconf
